### ISSUE TITLE
Encryption :)

### ISSUE THREAD

**Issue by ClaraCrazy** [deliever42/discord-token-grabber#5]
Look, I know it seems hard for most skids. But this code doesn't even seem stolen. How comes that to this day only two people, besides my unimportant self, have managed to deal with the new token encryption?

You simply don't care enough, never even noticed, or just cant figure it out? genuinely curious

**Comment by Sorrow446** [comment]
I wrote a dumper recently in Go. If you're interested: https://github.com/Sorrow446/Discord-Token-Dumper
Only works on the Windows desktop app or Windows Chrome at the moment.

**Comment by VerstreuteSeele** [comment]
@Sorrow446 im good. i was the first person to decrypt the new encrypted tokens and keep finding vulns in discord. I just love looking at gh skids' repos

**Comment by VerstreuteSeele** [comment]
if you however need help grabbing the tokens from the other 30ish browsers or from linux, or with any other application in that direction, for pentesting only ofc, feel free to hit me up

**Comment by Sorrow446** [comment]
Alright, no problem. I appreciate it. I don't think I'll be working on it again for a while tbh.
